version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always

  exporter1:
    image: prom/node-exporter:latest
    container_name: node-exporter1
    ports:
      - 9101:9100
    restart: always

  exporter2:
    image: prom/node-exporter:latest
    container_name: node-exporter2
    ports:
      - 9102:9100
    restart: always

  exporter3:
    image: prom/node-exporter:latest
    container_name: node-exporter3
    ports:
      - 9103:9100
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: always

  alertmanager:
    image: prom/alertmanager
    container_name: alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command: "--config.file=/etc/alertmanager/config.yaml"
    ports:
      - 9093:9093
    restart: always
